# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-greatexpectations",
        "name": "Great Expectations",
        "description": 'Provider package for Great Expectations integration.\nGreat Expectations (GX) is an open source Python-based data validation framework. You can test your data by\nexpressing what you "expect" from it as simple declarative statements in JSON or YAML, then run validations\nusing those Expectation Suites against data\n',
        "integrations": [
            {
                "integration-name": "Great Expectations",
                "external-doc-url": "https://greatexpectations.io/gx-core/",
                "logo": "/docs/integration-logos/GreatExpectations.png",
                "how-to-guide": [
                    "/docs/apache-airflow-providers-greatexpectations/operators/greatexpectations.rst"
                ],
                "tags": ["software"],
            }
        ],
        "operators": [
            {
                "integration-name": "Great Expectations",
                "python-modules": [
                    "airflow.providers.greatexpectations.operators.greatexpectations",
                    "airflow.providers.greatexpectations.operators.validate_batch",
                    "airflow.providers.greatexpectations.operators.validate_checkpoint",
                    "airflow.providers.greatexpectations.operators.validate_dataframe",
                ],
            }
        ],
        "hooks": [
            {
                "integration-name": "Great Expectations",
                "python-modules": ["airflow.providers.greatexpectations.hooks.gx_cloud"],
            }
        ],
    }
