export const DAGS_WITH_RECENT_FAILURES = [
  {
    id: "1",
    dagId: "Alerting_E2E_Test_azure_DND",
    time: "2 minutes ago",
    recentRuns: [
      {
        id: "1",
        time: "2 minutes ago",
        state: "failed",
        duration: 100,
        summary: "Task 'check_status' exceeded its execution timeout. Suggest investigating recent environment changes or data volume spikes.",
      },
      {
        id: "2",
        time: "15 minutes ago",
        state: "success",
        duration: 85,
      },
      {
        id: "3",
        time: "32 minutes ago",
        state: "success",
        duration: 92,
      },
      {
        id: "4",
        time: "47 minutes ago",
        state: "failed",
        duration: 103,
        summary: "Task 'validate_data' failed due to schema mismatch. Check upstream data source for recent changes.",
      },
      {
        id: "5",
        time: "1 hour ago",
        state: "success",
        duration: 88,
      },
      {
        id: "6",
        time: "1 hour 15 minutes ago",
        state: "success",
        duration: 90,
      },
      {
        id: "7",
        time: "1 hour 30 minutes ago",
        state: "failed",
        duration: 45,
        summary: "Task 'fetch_api_data' encountered connection timeout. Network latency detected.",
      },
      {
        id: "8",
        time: "1 hour 45 minutes ago",
        state: "success",
        duration: 87,
      },
      {
        id: "9",
        time: "2 hours ago",
        state: "success",
        duration: 91,
      },
      {
        id: "10",
        time: "2 hours 15 minutes ago",
        state: "success",
        duration: 89,
      },
      {
        id: "11",
        time: "2 hours 30 minutes ago",
        state: "success",
        duration: 93,
      },
      {
        id: "12",
        time: "2 hours 45 minutes ago",
        state: "failed",
        duration: 67,
        summary: "Task 'process_batch' encountered out of memory error. Consider reducing batch size or increasing worker memory.",
      },
      {
        id: "13",
        time: "3 hours ago",
        state: "success",
        duration: 86,
      },
      {
        id: "14",
        time: "3 hours 15 minutes ago",
        state: "success",
        duration: 94,
      },
      {
        id: "15",
        time: "3 hours 30 minutes ago",
        state: "success",
        duration: 89,
      },
      {
        id: "16",
        time: "3 hours 45 minutes ago",
        state: "failed",
        duration: 52,
        summary: "Authentication failed when accessing Azure storage. Verify service principal credentials are up to date.",
      },
      {
        id: "17",
        time: "4 hours ago",
        state: "success",
        duration: 91,
      },
      {
        id: "18",
        time: "4 hours 15 minutes ago",
        state: "success",
        duration: 88,
      },
      {
        id: "19",
        time: "4 hours 30 minutes ago",
        state: "success",
        duration: 90,
      },
      {
        id: "20",
        time: "4 hours 45 minutes ago",
        state: "success",
        duration: 92,
      },
    ],
  },
  {
    id: "2",
    dagId: "Data_Pipeline_ETL_Production",
    time: "14 minutes ago",
    recentRuns: [
      {
        id: "1",
        time: "14 minutes ago",
        state: "failed",
        duration: 145,
        summary: "The 'extract_data' task failed due to an invalid API response. Verify connectivity and the API key configuration.",
      },
      {
        id: "2",
        time: "30 minutes ago",
        state: "success",
        duration: 120,
      },
      {
        id: "3",
        time: "45 minutes ago",
        state: "failed",
        duration: 130,
        summary: "Database connection pool exhausted. Consider increasing max_connections or optimizing query patterns.",
      },
      {
        id: "4",
        time: "1 hour ago",
        state: "success",
        duration: 125,
      },
      {
        id: "5",
        time: "1 hour 15 minutes ago",
        state: "success",
        duration: 118,
      },
      {
        id: "6",
        time: "1 hour 30 minutes ago",
        state: "success",
        duration: 122,
      },
      {
        id: "7",
        time: "1 hour 45 minutes ago",
        state: "success",
        duration: 119,
      },
      {
        id: "8",
        time: "2 hours ago",
        state: "failed",
        duration: 95,
        summary: "Memory limit exceeded during data transformation. Review dataset size or increase worker memory allocation.",
      },
      {
        id: "9",
        time: "2 hours 15 minutes ago",
        state: "success",
        duration: 123,
      },
      {
        id: "10",
        time: "2 hours 30 minutes ago",
        state: "success",
        duration: 121,
      },
      {
        id: "11",
        time: "2 hours 45 minutes ago",
        state: "success",
        duration: 124,
      },
      {
        id: "12",
        time: "3 hours ago",
        state: "failed",
        duration: 110,
        summary: "Data validation failed. Detected duplicate records in source dataset. Check ETL deduplication logic.",
      },
      {
        id: "13",
        time: "3 hours 15 minutes ago",
        state: "success",
        duration: 126,
      },
      {
        id: "14",
        time: "3 hours 30 minutes ago",
        state: "success",
        duration: 120,
      },
      {
        id: "15",
        time: "3 hours 45 minutes ago",
        state: "success",
        duration: 127,
      },
      {
        id: "16",
        time: "4 hours ago",
        state: "failed",
        duration: 98,
        summary: "Transformation step timed out processing large CSV file. Consider chunking or parallel processing.",
      },
      {
        id: "17",
        time: "4 hours 15 minutes ago",
        state: "success",
        duration: 122,
      },
      {
        id: "18",
        time: "4 hours 30 minutes ago",
        state: "success",
        duration: 128,
      },
      {
        id: "19",
        time: "4 hours 45 minutes ago",
        state: "success",
        duration: 119,
      },
      {
        id: "20",
        time: "5 hours ago",
        state: "success",
        duration: 125,
      },
    ],
  },
  {
    id: "3",
    dagId: "ML_Model_Training_Daily",
    time: "42 minutes ago",
    recentRuns: [
      {
        id: "1",
        time: "42 minutes ago",
        state: "failed",
        duration: 210,
        summary: "DAG run failed: Task 'process_data' encountered a Python exception (KeyError: 'user_id'). Review the task's parsing logic.",
      },
      {
        id: "2",
        time: "1 hour ago",
        state: "success",
        duration: 195,
      },
      {
        id: "3",
        time: "1 hour 20 minutes ago",
        state: "success",
        duration: 200,
      },
      {
        id: "4",
        time: "1 hour 40 minutes ago",
        state: "success",
        duration: 198,
      },
      {
        id: "5",
        time: "2 hours ago",
        state: "failed",
        duration: 155,
        summary: "Training data quality check failed. Found 15% null values in critical features. Data pipeline may need attention.",
      },
      {
        id: "6",
        time: "2 hours 20 minutes ago",
        state: "success",
        duration: 202,
      },
      {
        id: "7",
        time: "2 hours 40 minutes ago",
        state: "success",
        duration: 197,
      },
      {
        id: "8",
        time: "3 hours ago",
        state: "success",
        duration: 199,
      },
      {
        id: "9",
        time: "3 hours 20 minutes ago",
        state: "success",
        duration: 203,
      },
      {
        id: "10",
        time: "3 hours 40 minutes ago",
        state: "failed",
        duration: 178,
        summary: "Model convergence failed. Hyperparameters may need tuning or training data distribution has shifted.",
      },
      {
        id: "11",
        time: "4 hours ago",
        state: "success",
        duration: 196,
      },
      {
        id: "12",
        time: "4 hours 20 minutes ago",
        state: "success",
        duration: 201,
      },
      {
        id: "13",
        time: "4 hours 40 minutes ago",
        state: "success",
        duration: 204,
      },
      {
        id: "14",
        time: "5 hours ago",
        state: "failed",
        duration: 165,
        summary: "GPU memory allocation failed. Multiple training jobs may be competing for resources.",
      },
      {
        id: "15",
        time: "5 hours 20 minutes ago",
        state: "success",
        duration: 198,
      },
      {
        id: "16",
        time: "5 hours 40 minutes ago",
        state: "success",
        duration: 205,
      },
      {
        id: "17",
        time: "6 hours ago",
        state: "success",
        duration: 197,
      },
      {
        id: "18",
        time: "6 hours 20 minutes ago",
        state: "failed",
        duration: 188,
        summary: "Feature engineering pipeline failed. Missing required columns in input dataset.",
      },
      {
        id: "19",
        time: "6 hours 40 minutes ago",
        state: "success",
        duration: 202,
      },
      {
        id: "20",
        time: "7 hours ago",
        state: "success",
        duration: 199,
      },
    ],
  },
  {
    id: "4",
    dagId: "Notification_Service_Sync",
    time: "1 hour ago",
    recentRuns: [
      {
        id: "1",
        time: "1 hour ago",
        state: "failed",
        duration: 62,
        summary: "The 'send_notification' task failed: SMTP server not reachable. Check server credentials and network access.",
      },
      {
        id: "2",
        time: "1 hour 15 minutes ago",
        state: "success",
        duration: 55,
      },
      {
        id: "3",
        time: "1 hour 30 minutes ago",
        state: "success",
        duration: 58,
      },
      {
        id: "4",
        time: "1 hour 45 minutes ago",
        state: "failed",
        duration: 48,
        summary: "Rate limit exceeded on email service provider. Implement exponential backoff or increase rate limits.",
      },
      {
        id: "5",
        time: "2 hours ago",
        state: "success",
        duration: 57,
      },
      {
        id: "6",
        time: "2 hours 15 minutes ago",
        state: "success",
        duration: 56,
      },
      {
        id: "7",
        time: "2 hours 30 minutes ago",
        state: "success",
        duration: 59,
      },
      {
        id: "8",
        time: "2 hours 45 minutes ago",
        state: "success",
        duration: 54,
      },
      {
        id: "9",
        time: "3 hours ago",
        state: "failed",
        duration: 35,
        summary: "Template rendering failed. Email template contains invalid variable references.",
      },
      {
        id: "10",
        time: "3 hours 15 minutes ago",
        state: "success",
        duration: 60,
      },
      {
        id: "11",
        time: "3 hours 30 minutes ago",
        state: "success",
        duration: 55,
      },
      {
        id: "12",
        time: "3 hours 45 minutes ago",
        state: "success",
        duration: 58,
      },
      {
        id: "13",
        time: "4 hours ago",
        state: "failed",
        duration: 42,
        summary: "Notification queue overflowed. Message broker capacity exceeded during peak load period.",
      },
      {
        id: "14",
        time: "4 hours 15 minutes ago",
        state: "success",
        duration: 57,
      },
      {
        id: "15",
        time: "4 hours 30 minutes ago",
        state: "success",
        duration: 59,
      },
      {
        id: "16",
        time: "4 hours 45 minutes ago",
        state: "success",
        duration: 56,
      },
      {
        id: "17",
        time: "5 hours ago",
        state: "failed",
        duration: 38,
        summary: "SSL certificate validation failed for SMTP connection. Certificate may have expired or needs renewal.",
      },
      {
        id: "18",
        time: "5 hours 15 minutes ago",
        state: "success",
        duration: 61,
      },
      {
        id: "19",
        time: "5 hours 30 minutes ago",
        state: "success",
        duration: 54,
      },
      {
        id: "20",
        time: "5 hours 45 minutes ago",
        state: "success",
        duration: 58,
      },
    ],
  },
  {
    id: "5",
    dagId: "Analytics_Report_Generator",
    time: "2 hours ago",
    recentRuns: [
      {
        id: "1",
        time: "2 hours ago",
        state: "failed",
        duration: 175,
        summary: "DAG interrupted: Upstream dependency 'wait_for_data' was not satisfied. Investigate the upstream data workflow for delays.",
      },
      {
        id: "2",
        time: "2 hours 20 minutes ago",
        state: "success",
        duration: 165,
      },
      {
        id: "3",
        time: "2 hours 40 minutes ago",
        state: "success",
        duration: 168,
      },
      {
        id: "4",
        time: "3 hours ago",
        state: "success",
        duration: 170,
      },
      {
        id: "5",
        time: "3 hours 20 minutes ago",
        state: "failed",
        duration: 142,
        summary: "Report generation timeout. Query complexity may have increased or database performance degraded.",
      },
      {
        id: "6",
        time: "3 hours 40 minutes ago",
        state: "success",
        duration: 167,
      },
      {
        id: "7",
        time: "4 hours ago",
        state: "success",
        duration: 169,
      },
      {
        id: "8",
        time: "4 hours 20 minutes ago",
        state: "success",
        duration: 166,
      },
      {
        id: "9",
        time: "4 hours 40 minutes ago",
        state: "success",
        duration: 171,
      },
      {
        id: "10",
        time: "5 hours ago",
        state: "success",
        duration: 164,
      },
      {
        id: "11",
        time: "5 hours 20 minutes ago",
        state: "success",
        duration: 172,
      },
      {
        id: "12",
        time: "5 hours 40 minutes ago",
        state: "failed",
        duration: 148,
        summary: "S3 bucket access denied. IAM permissions may have been modified or bucket policy changed.",
      },
      {
        id: "13",
        time: "6 hours ago",
        state: "success",
        duration: 168,
      },
      {
        id: "14",
        time: "6 hours 20 minutes ago",
        state: "success",
        duration: 173,
      },
      {
        id: "15",
        time: "6 hours 40 minutes ago",
        state: "success",
        duration: 166,
      },
      {
        id: "16",
        time: "7 hours ago",
        state: "failed",
        duration: 135,
        summary: "Analytics aggregation failed. Detected schema change in source tables breaking existing queries.",
      },
      {
        id: "17",
        time: "7 hours 20 minutes ago",
        state: "success",
        duration: 170,
      },
      {
        id: "18",
        time: "7 hours 40 minutes ago",
        state: "success",
        duration: 167,
      },
      {
        id: "19",
        time: "8 hours ago",
        state: "success",
        duration: 169,
      },
      {
        id: "20",
        time: "8 hours 20 minutes ago",
        state: "success",
        duration: 165,
      },
    ],
  },
];