#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""
Add partition_key field.

Revision ID: cbd203f1e5ec
Revises: 15d84ca19038
Create Date: 2025-09-17 09:48:43.202614

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbd203f1e5ec"
down_revision = "15d84ca19038"
branch_labels = None
depends_on = None
airflow_version = "3.2.0"


def upgrade():
    """Apply Add partition_key field."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("partition_key", sa.String(length=250), nullable=True))

    with op.batch_alter_table("dag_run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("partition_key", sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """Unapply Add partition_key field."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dag_run", schema=None) as batch_op:
        batch_op.drop_column("partition_key")

    with op.batch_alter_table("asset_event", schema=None) as batch_op:
        batch_op.drop_column("partition_key")

    # ### end Alembic commands ###
