export const connectionsData = {
  environmentObjects: [
    {
      id: "cm2l1ro8z006101q35w36mh6g",
      scope: "DEPLOYMENT",
      scopeEntityId: "clx9g3xak000w01ksr29jl6f2",
      objectType: "CONNECTION",
      objectKey: "asd",
      connection: {
        connectionAuthType: {
          id: "github_base",
          name: "GitHub",
          authMethodName: "",
          airflowType: "github",
          description: "Configure a GitHub connection",
          providerPackageName: "apache-airflow-providers-github",
          providerLogo:
            "https://astro-provider-logos.s3.us-east-2.amazonaws.com/apache-airflow-providers-github.png",
          parameters: [
            {
              airflowParamName: "password",
              friendlyName: "Access Token",
              dataType: "str",
              isRequired: true,
              isSecret: true,
              description: "Personal access token with required permissions.",
              example: "ghp_abcdefghijk1234567890",
              isInExtra: false,
            },
            {
              airflowParamName: "host",
              friendlyName: "Host",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description:
                "Specify the GitHub Enterprise URL when connecting to a GitHub Enterprise account.",
              example: "https://github.mydomain.com",
              isInExtra: false,
            },
          ],
        },
        type: "github",
      },
      links: [
        {
          scope: "DEPLOYMENT",
          scopeEntityId: "clyz2mshy00e501p1vchz64yx",
          connectionOverrides: {},
        },
      ],
      createdAt: "2024-10-22T22:58:55.237Z",
      updatedAt: "2024-10-22T22:59:17.321Z",
      createdBy: {
        id: "cl6zt14k7480291jzcdy0n8xzi",
        subjectType: "USER",
        username: "ryan@astronomer.io",
        fullName: "Ryan Hamilton",
        avatarUrl:
          "https://s.gravatar.com/avatar/6dea52b82fbf78cb2eefda489027ef79?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Frh.png",
      },
      updatedBy: {
        id: "cl6zt14k7480291jzcdy0n8xzi",
        subjectType: "USER",
        username: "ryan@astronomer.io",
        fullName: "Ryan Hamilton",
        avatarUrl:
          "https://s.gravatar.com/avatar/6dea52b82fbf78cb2eefda489027ef79?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Frh.png",
      },
    },
    {
      id: "cmdz3488k02wa01l5ckjq8eqx",
      scope: "WORKSPACE",
      scopeEntityId: "clx9g3xak000w01ksr29jl6f2",
      objectType: "CONNECTION",
      objectKey: "snowflake_conn",
      connection: {
        connectionAuthType: {
          id: "snowflake_private_key_content",
          name: "Snowflake",
          authMethodName: "Private Key (Content)",
          airflowType: "snowflake",
          description:
            "Snowflake is a cloud-based data-warehousing platform that supports both structured and semi-structured data.",
          providerPackageName: "apache-airflow-providers-snowflake",
          providerLogo:
            "https://astro-provider-logos.s3.us-east-2.amazonaws.com/apache-airflow-providers-snowflake.png",
          parameters: [
            {
              airflowParamName: "login",
              friendlyName: "Username",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "The username to use for authenticating against Snowflake.",
              example: "my_username",
              isInExtra: false,
            },
            {
              airflowParamName: "schema",
              friendlyName: "Default schema",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default schema to use for the connection.",
              example: "my_schema",
              isInExtra: false,
            },
            {
              airflowParamName: "account",
              friendlyName: "Account Locator",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "The unique identifier of the Snowflake account to connect to.",
              example: "GP12345",
              isInExtra: true,
            },
            {
              airflowParamName: "database",
              friendlyName: "Database",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default database to use for the connection.",
              example: "my_database",
              isInExtra: true,
            },
            {
              airflowParamName: "region",
              friendlyName: "Region",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the Snowflake region to connect to.",
              example: "my_region",
              isInExtra: true,
            },
            {
              airflowParamName: "warehouse",
              friendlyName: "Warehouse",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default warehouse to use for the connection.",
              example: "my_warehouse",
              isInExtra: true,
            },
            {
              airflowParamName: "role",
              friendlyName: "Role",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default role to use for the connection.",
              example: "my_role",
              isInExtra: true,
            },
            {
              airflowParamName: "authenticator",
              friendlyName: "Authenticator",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The authenticator to use for the connection.",
              example: "my_authenticator",
              isInExtra: true,
            },
            {
              airflowParamName: "session_parameters",
              friendlyName: "Session parameters",
              dataType: "dict",
              isRequired: false,
              isSecret: false,
              description: "The session parameters to use for the connection.",
              example: "{'QUERY_TAG': 'airflow'}",
              isInExtra: true,
            },
            {
              airflowParamName: "insecure_mode",
              friendlyName: "Insecure mode",
              dataType: "bool",
              isRequired: false,
              isSecret: false,
              description: "Whether to use insecure mode for the connection.",
              example: "False",
              isInExtra: true,
            },
            {
              airflowParamName: "password",
              friendlyName: "Private Key Passphrase",
              dataType: "str",
              isRequired: false,
              isSecret: true,
              description: "The passphrase for decrypting the private key.",
              example: "my_private_key_passphrase",
              isInExtra: false,
            },
            {
              airflowParamName: "private_key_content",
              friendlyName: "Private Key Content",
              dataType: "longtext",
              isRequired: true,
              isSecret: true,
              description:
                "The content of the private key to use for authenticating against Snowflake. For Snowflake Provider v6.3.0 and above, your private key content must be pasted in as a base64 encoded string.",
              example:
                "Snowflake Provider v6.3.0 and above:\n  LS0tLS1CRUdJTiBFTkNSWVBURUQgUFJJVkFURSBLRVktLS0tLQpNSUlGSFRC...\n\nSnowflake Provider below v6.3.0:\n  -----BEGIN RSA PRIVATE KEY-----\n  MIIE6T...\n  -----END RSA PRIVATE KEY-----\n",
              isInExtra: true,
            },
          ],
        },
        type: "snowflake",
        login: "WILLIAMSHI",
        extra: {
          account: "FY02423-GP21411",
        },
      },
      createdAt: "2025-08-05T22:02:12.79Z",
      updatedAt: "2025-08-05T22:02:17.555Z",
      createdBy: {
        id: "cm8nliy1v020n01mirihbvj5y",
        subjectType: "USER",
        username: "william.shi@astronomer.io",
        fullName: "William Shi",
        avatarUrl:
          "https://lh3.googleusercontent.com/a/ACg8ocJ2NpziJkxWB7meKW490TElsJLPn5SnqwQX3XmqLOZ4JjUdsg=s96-c",
      },
      updatedBy: {
        id: "cm8nliy1v020n01mirihbvj5y",
        subjectType: "USER",
        username: "william.shi@astronomer.io",
        fullName: "William Shi",
        avatarUrl:
          "https://lh3.googleusercontent.com/a/ACg8ocJ2NpziJkxWB7meKW490TElsJLPn5SnqwQX3XmqLOZ4JjUdsg=s96-c",
      },
    },
    {
      id: "cmbjoijki0lmk01psxjcuwla5",
      scope: "WORKSPACE",
      scopeEntityId: "clx9g3xak000w01ksr29jl6f2",
      objectType: "CONNECTION",
      objectKey: "vandy_databricks",
      connection: {
        connectionAuthType: {
          id: "databricks_base",
          name: "Databricks",
          authMethodName: "",
          airflowType: "databricks",
          description: "Configure a connection to Databricks.",
          providerPackageName: "apache-airflow-providers-databricks",
          providerLogo:
            "https://astro-provider-logos.s3.us-east-2.amazonaws.com/apache-airflow-providers-databricks.png",
          parameters: [
            {
              airflowParamName: "host",
              friendlyName: "Host",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "Databricks host URL",
              example: "https://my-cluster.cloud.databricks.com/",
              isInExtra: false,
            },
            {
              airflowParamName: "password",
              friendlyName: "Password",
              dataType: "str",
              isRequired: true,
              isSecret: true,
              description: "Databricks personal access token",
              example: "wJalrXUtnFEMI%2FK7MDENGbPxRfiCYEXAMPLEKEY",
              isInExtra: false,
            },
            {
              airflowParamName: "http_path",
              friendlyName: "HTTP Path",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "Cluster HTTP Path",
              example: "/sql/1.0/warehouses/foobar",
              isInExtra: true,
            },
          ],
        },
        type: "databricks",
        host: "adb-410971030321470.10.azuredatabricks.net",
      },
      links: [
        {
          scope: "DEPLOYMENT",
          scopeEntityId: "cmbh39k15000j01mk2092ez9f",
          connectionOverrides: {},
        },
      ],
      createdAt: "2025-06-05T17:57:29.108Z",
      updatedAt: "2025-08-06T03:28:51.177Z",
      createdBy: {
        id: "cl7qqe4tf264442d28fttoe7g8",
        subjectType: "USER",
        username: "vandy.liu@astronomer.io",
        fullName: "Vandy Liu",
        avatarUrl:
          "https://s.gravatar.com/avatar/ea0265af113c7429c02cf1de98f03552?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fvl.png",
      },
      updatedBy: {
        id: "ckx6ogzn059721g078uxv3a7k",
        subjectType: "USER",
        username: "frank.ye@astronomer.io",
        fullName: "Frank Ye",
        avatarUrl:
          "https://s.gravatar.com/avatar/4aeef6ff7b072193b1d2d9fdf9c2be1f?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Ffy.png",
      },
    },
    {
      id: "cmbh3kj7u005u01lc41gcf14a",
      scope: "WORKSPACE",
      scopeEntityId: "clx9g3xak000w01ksr29jl6f2",
      objectType: "CONNECTION",
      objectKey: "vandyliu",
      connection: {
        connectionAuthType: {
          id: "snowflake_private_key_content",
          name: "Snowflake",
          authMethodName: "Private Key (Content)",
          airflowType: "snowflake",
          description:
            "Snowflake is a cloud-based data-warehousing platform that supports both structured and semi-structured data.",
          providerPackageName: "apache-airflow-providers-snowflake",
          providerLogo:
            "https://astro-provider-logos.s3.us-east-2.amazonaws.com/apache-airflow-providers-snowflake.png",
          parameters: [
            {
              airflowParamName: "login",
              friendlyName: "Username",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "The username to use for authenticating against Snowflake.",
              example: "my_username",
              isInExtra: false,
            },
            {
              airflowParamName: "schema",
              friendlyName: "Default schema",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default schema to use for the connection.",
              example: "my_schema",
              isInExtra: false,
            },
            {
              airflowParamName: "account",
              friendlyName: "Account Locator",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "The unique identifier of the Snowflake account to connect to.",
              example: "GP12345",
              isInExtra: true,
            },
            {
              airflowParamName: "database",
              friendlyName: "Database",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default database to use for the connection.",
              example: "my_database",
              isInExtra: true,
            },
            {
              airflowParamName: "region",
              friendlyName: "Region",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the Snowflake region to connect to.",
              example: "my_region",
              isInExtra: true,
            },
            {
              airflowParamName: "warehouse",
              friendlyName: "Warehouse",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default warehouse to use for the connection.",
              example: "my_warehouse",
              isInExtra: true,
            },
            {
              airflowParamName: "role",
              friendlyName: "Role",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The name of the default role to use for the connection.",
              example: "my_role",
              isInExtra: true,
            },
            {
              airflowParamName: "authenticator",
              friendlyName: "Authenticator",
              dataType: "str",
              isRequired: false,
              isSecret: false,
              description: "The authenticator to use for the connection.",
              example: "my_authenticator",
              isInExtra: true,
            },
            {
              airflowParamName: "session_parameters",
              friendlyName: "Session parameters",
              dataType: "dict",
              isRequired: false,
              isSecret: false,
              description: "The session parameters to use for the connection.",
              example: "{'QUERY_TAG': 'airflow'}",
              isInExtra: true,
            },
            {
              airflowParamName: "insecure_mode",
              friendlyName: "Insecure mode",
              dataType: "bool",
              isRequired: false,
              isSecret: false,
              description: "Whether to use insecure mode for the connection.",
              example: "False",
              isInExtra: true,
            },
            {
              airflowParamName: "password",
              friendlyName: "Private Key Passphrase",
              dataType: "str",
              isRequired: false,
              isSecret: true,
              description: "The passphrase for decrypting the private key.",
              example: "my_private_key_passphrase",
              isInExtra: false,
            },
            {
              airflowParamName: "private_key_content",
              friendlyName: "Private Key Content",
              dataType: "longtext",
              isRequired: true,
              isSecret: true,
              description:
                "The content of the private key to use for authenticating against Snowflake. For Snowflake Provider v6.3.0 and above, your private key content must be pasted in as a base64 encoded string.",
              example:
                "Snowflake Provider v6.3.0 and above:\n  LS0tLS1CRUdJTiBFTkNSWVBURUQgUFJJVkFURSBLRVktLS0tLQpNSUlGSFRC...\n\nSnowflake Provider below v6.3.0:\n  -----BEGIN RSA PRIVATE KEY-----\n  MIIE6T...\n  -----END RSA PRIVATE KEY-----\n",
              isInExtra: true,
            },
          ],
        },
        type: "snowflake",
        schema: "VANDYLIU",
        login: "VANDYLIU",
        extra: {
          account: "GP21411",
          database: "SANDBOX",
          region: "us-east-1",
          role: "VANDYLIU",
          warehouse: "QA",
        },
      },
      links: [
        {
          scope: "DEPLOYMENT",
          scopeEntityId: "cmbh39k15000j01mk2092ez9f",
          connectionOverrides: {},
        },
      ],
      createdAt: "2025-06-03T22:35:37.676Z",
      updatedAt: "2025-08-06T03:29:15.046Z",
      createdBy: {
        id: "cl7qqe4tf264442d28fttoe7g8",
        subjectType: "USER",
        username: "vandy.liu@astronomer.io",
        fullName: "Vandy Liu",
        avatarUrl:
          "https://s.gravatar.com/avatar/ea0265af113c7429c02cf1de98f03552?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fvl.png",
      },
      updatedBy: {
        id: "ckx6ogzn059721g078uxv3a7k",
        subjectType: "USER",
        username: "frank.ye@astronomer.io",
        fullName: "Frank Ye",
        avatarUrl:
          "https://s.gravatar.com/avatar/4aeef6ff7b072193b1d2d9fdf9c2be1f?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Ffy.png",
      },
    },
    {
      id: "cmeap652804z801l7ea7a3r9l",
      scope: "WORKSPACE",
      scopeEntityId: "clx9g3xak000w01ksr29jl6f2",
      objectType: "CONNECTION",
      objectKey: "observe_remote_execution_OL_e2e_tests_s3_access",
      connection: {
        connectionAuthType: {
          id: "aws_iam",
          name: "AWS",
          authMethodName: "Assume Role",
          airflowType: "aws",
          description:
            "Configure a connection to AWS Services using an existing IAM Role. Ensure your Astro Deployment's Workload Identity has been authorized to assume this role via its trust relationship.",
          providerPackageName: "apache-airflow-providers-amazon",
          providerLogo:
            "https://astro-provider-logos.s3.us-east-2.amazonaws.com/apache-airflow-providers-amazon.png",
          parameters: [
            {
              airflowParamName: "role_arn",
              friendlyName: "IAM Role ARN",
              dataType: "str",
              isRequired: true,
              isSecret: false,
              description: "AWS IAM Role ARN",
              example: "arn:aws:iam::123467890:role/workload-identity-role-name-123",
              isInExtra: true,
            },
          ],
        },
        type: "aws",
        extra: {
          role_arn:
            "arn:aws:iam::418684279750:role/observe_remote_execution_OL_e2e_tests_nodegroup_permissions",
        },
      },
      createdAt: "2025-08-14T01:05:01.473Z",
      updatedAt: "2025-08-14T01:05:01.473Z",
      createdBy: {
        id: "cmabpzugt019v01jfm2pg8isx",
        subjectType: "USER",
      },
      updatedBy: {
        id: "cmabpzugt019v01jfm2pg8isx",
        subjectType: "USER",
      },
    },
  ],
  totalCount: 5,
  offset: 0,
  limit: 20,
};
